version: '3.0'

services:
  db:
    image: mysql
    restart: always
    container_name: todo_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123123}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: todo_phpmyadmin
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db